<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="20190729_161354" timestamp="2019-07-29T16:13:54" time="21.018" tests="9" errors="1">
  <testsuite id="1" name="secondAssignment" package="secondAssignment" hostname="ATMECSINDT-043" timestamp="2019-07-29T16:13:56" time="18.890" tests="9" errors="1">
    <properties>
      <property name="Run From" value="ATMECSINDT-043" />
      <property name="Run OS" value="amd64 Windows 10 10.0" />
      <property name="Run User" value="deepankar.pathal" />
      <property name="Iteration" value="1 of 1" />
      <property name="Script" value="secondAssignment.xlsx" />
      <property name="Logs" value="C:\projects\secondAssignment\output\20190729_161354\logs\nexial-20190729_161354.log" />
      <property name="Data File" value="secondAssignment.data.xlsx" />
      <property name="DataSheet(s)" value="#default" />
      <property name="JAVA_OPT" value="-Dorg.apache.poi.util.POILogger=org.apache.poi.util.NullLogger" />
      <property name="runtime args" value="-script C:\projects\secondAssignment\artifact\script\secondAssignment.xlsx -scenario Scenario2" />
    </properties>
    <testcase id="Activity 1" name="Activity 1" classname="Scenario2" timestamp="2019-07-29T16:13:58" time="16.536">
      <failure type="failure found in test activity" message="1 of 9 FAILED. Check C:\projects\secondAssignment\output\20190729_161354\secondAssignment.20190729_161356.001.xlsx for execution result, C:\projects\secondAssignment\output\20190729_161354\logs\nexial-20190729_161354.log for execution logs" />
      <system-out>Total : 9
Passed: 8
Failed: 1
Output: C:\projects\secondAssignment\output\20190729_161354\secondAssignment.20190729_161356.001.xlsx
Logs  : C:\projects\secondAssignment\output\20190729_161354\logs\nexial-20190729_161354.log</system-out>
    </testcase>
  </testsuite>
</testsuites>
